"""
agent_workflow.py
-----------------
LangGraph-based Agentic Self-Healing workflow for Databricks schema drift.

This module defines a four-agent pipeline that automatically detects, diagnoses,
tests, and fixes schema drift failures in Databricks Delta Lake tables:

    Detective  →  Engineer  →  QA ──(pass)──→  Deploy
                     ↑                |
                     └───(fail/rewrite)┘

Agents
------
1. detective_agent  – Queries Unity Catalog to identify the exact columns that
                      drifted (new column, type change, or dropped field).
2. engineer_agent   – Proposes a fix: either a PySpark `mergeSchema` option or
                      an explicit `ALTER TABLE` DDL, depending on QA feedback.
3. qa_agent         – Spins up a Zero-Copy Clone of the production Delta table
                      and validates the proposed fix in an isolated sandbox.
4. deployment_agent – Applies the approved fix to production via the Unity
                      Catalog REST API and restarts the failed Databricks job.

Usage
-----
Invoke the compiled graph directly::

    asyncio.run(run_healing_workflow(job_id="12345", error_logs="..."))

Or trigger it through the FastAPI webhook in ``api.py``.
"""

import asyncio
from typing import TypedDict

from langgraph.graph import StateGraph, START, END


# ---------------------------------------------------------------------------
# State definition
# ---------------------------------------------------------------------------

class DatabricksPipelineState(TypedDict):
    """Shared state passed between every agent node in the graph.

    Attributes
    ----------
    job_id:
        The Databricks Jobs API job identifier that failed.
    error_logs:
        Raw log output captured from the failed job run, typically containing
        a Spark ``AnalysisException`` with schema mismatch details.
    drift_details:
        Human-readable summary of the detected schema drift produced by the
        Detective Agent (e.g. "new column 'loyalty_tier' (StringType) added").
    proposed_sql_fix:
        DDL statement (e.g. ``ALTER TABLE … ADD COLUMN …``) generated by the
        Engineer Agent, or ``"None"`` when no DDL change is needed.
    proposed_pyspark_fix:
        Updated PySpark write code generated by the Engineer Agent, or a
        descriptive string when no PySpark change is required.
    qa_passed:
        ``True`` if the QA Agent approved the proposed fix on the cloned table,
        ``False`` otherwise.
    qa_feedback:
        Plain-text explanation returned by the QA Agent describing why the fix
        passed or failed governance checks.
    fix_strategy:
        Tracks the Engineer Agent's chosen fix strategy: ``"merge_schema"`` for
        the implicit Delta Lake option or ``"alter_table"`` for an explicit DDL.
        Used by the QA Agent to apply governance rules without brittle string
        matching on generated code.
    status_message:
        Final human-readable summary set by the Deploy Agent once the pipeline
        has been healed and the job restarted.
    """

    job_id: str
    error_logs: str
    drift_details: str
    proposed_sql_fix: str
    proposed_pyspark_fix: str
    fix_strategy: str  # "merge_schema" | "alter_table"
    qa_passed: bool
    qa_feedback: str
    status_message: str


# ---------------------------------------------------------------------------
# Agent nodes
# ---------------------------------------------------------------------------

async def detective_agent(state: DatabricksPipelineState) -> dict:
    """Analyze the failed job logs and identify the schema drift.

    In a production deployment this agent uses an MCP tool connected to a
    Databricks SQL Warehouse to run::

        DESCRIBE TABLE <catalog>.<schema>.<table>

    It then compares the Unity Catalog schema against the incoming DataFrame
    schema (extracted from the error logs or by re-reading the source) to
    produce a precise, structured description of the drift.

    Parameters
    ----------
    state:
        Current pipeline state.  Reads ``job_id`` and ``error_logs``.

    Returns
    -------
    dict
        ``{"drift_details": <str>}`` describing the detected drift.
    """
    print(f"[{state['job_id']}] 🕵️  Detective: Analyzing Spark AnalysisException...")

    # --- Production replacement -------------------------------------------
    # tool_result = await mcp_databricks.run_sql(
    #     f"DESCRIBE TABLE main.sales.customers"
    # )
    # incoming_schema = extract_schema_from_logs(state["error_logs"])
    # drift_info = compare_schemas(tool_result, incoming_schema)
    # ----------------------------------------------------------------------

    await asyncio.sleep(1)

    drift_info = (
        "Schema Drift Detected: Incoming DataFrame contains new column "
        "'loyalty_tier' (StringType) not present in target Delta table "
        "'main.sales.customers'."
    )

    return {"drift_details": drift_info}


async def engineer_agent(state: DatabricksPipelineState) -> dict:
    """Formulate a Delta Lake schema evolution strategy to fix the drift.

    On the **first pass** the engineer proposes the least-invasive fix:
    enabling ``mergeSchema`` on the PySpark write so Delta Lake absorbs the
    new column automatically.

    If the QA Agent rejects that approach (e.g. because data-governance policy
    forbids implicit schema evolution), the engineer escalates to an explicit
    ``ALTER TABLE`` DDL that gives full control over the change.

    Parameters
    ----------
    state:
        Current pipeline state.  Reads ``drift_details``, ``qa_passed``, and
        ``qa_feedback`` to decide which strategy to apply.

    Returns
    -------
    dict
        ``{"proposed_sql_fix": <str>, "proposed_pyspark_fix": <str>}``
    """
    print(
        f"[{state['job_id']}] 🛠️  Engineer: "
        "Formulating Delta Lake schema evolution strategy..."
    )

    await asyncio.sleep(1)

    # Second attempt: QA rejected mergeSchema — use explicit DDL instead.
    if state.get("qa_feedback") and not state.get("qa_passed", False):
        sql_fix = "ALTER TABLE main.sales.customers ADD COLUMN loyalty_tier STRING;"
        pyspark_fix = (
            "No changes to PySpark write needed; "
            "schema explicitly evolved via ALTER TABLE."
        )
        fix_strategy = "alter_table"
    else:
        # First attempt: let Delta Lake handle the new column automatically.
        sql_fix = "None"
        pyspark_fix = (
            'df.write.format("delta")\n'
            '  .mode("append")\n'
            '  .option("mergeSchema", "true")\n'
            '  .saveAsTable("main.sales.customers")'
        )
        fix_strategy = "merge_schema"

    return {
        "proposed_sql_fix": sql_fix,
        "proposed_pyspark_fix": pyspark_fix,
        "fix_strategy": fix_strategy,
    }


async def qa_agent(state: DatabricksPipelineState) -> dict:
    """Validate the proposed fix using a Zero-Copy Clone of the Delta table.

    This agent enforces enterprise data-governance policies before any change
    reaches production.  It performs the following steps in a real deployment:

    1. Creates an isolated sandbox clone::

           CREATE TABLE dev.sandbox.customers_clone
           CLONE main.sales.customers;

    2. Applies the Engineer's proposed PySpark or SQL fix against the clone.
    3. Runs a data-quality check (row counts, NULL rates, type assertions).
    4. Drops the clone when finished to free storage.

    A key governance rule modelled here: implicit ``mergeSchema=True`` is
    **rejected** because it could silently absorb upstream garbage columns.
    All schema changes must be declared through explicit ``ALTER TABLE`` DDL.

    Parameters
    ----------
    state:
        Current pipeline state.  Reads ``job_id``, ``proposed_pyspark_fix``,
        and ``proposed_sql_fix``.

    Returns
    -------
    dict
        ``{"qa_passed": bool, "qa_feedback": str}``
    """
    print(f"[{state['job_id']}] 🧪  QA: Cloning Delta table and testing fix...")

    # --- Production replacement -------------------------------------------
    # await mcp_databricks.run_sql(
    #     "CREATE TABLE dev.sandbox.customers_clone CLONE main.sales.customers"
    # )
    # await mcp_databricks.run_pyspark(state["proposed_pyspark_fix"], target="clone")
    # quality_ok = await run_data_quality_checks("dev.sandbox.customers_clone")
    # await mcp_databricks.run_sql("DROP TABLE dev.sandbox.customers_clone")
    # ----------------------------------------------------------------------

    await asyncio.sleep(1)

    # Use the explicit fix_strategy flag set by the Engineer Agent rather than
    # matching strings inside generated code, which would be brittle.
    if state.get("fix_strategy") == "merge_schema":
        feedback = (
            "QA Failed: Data-governance policy forbids implicit 'mergeSchema'. "
            "Use an explicit ALTER TABLE statement to document the change."
        )
        print(f"   -> QA Rejected: {feedback}")
        return {"qa_passed": False, "qa_feedback": feedback}

    feedback = (
        "QA Passed: ALTER TABLE applied successfully to sandbox clone. "
        "Row counts match; data insertion succeeded."
    )
    print(f"   -> QA Approved: {feedback}")
    return {"qa_passed": True, "qa_feedback": feedback}


async def deployment_agent(state: DatabricksPipelineState) -> dict:
    """Apply the approved fix to production and restart the Databricks job.

    Production steps performed by this agent:

    1. Executes the approved DDL against the Unity Catalog production table::

           ALTER TABLE main.sales.customers ADD COLUMN loyalty_tier STRING;

    2. Commits the updated PySpark notebook/script to the Databricks Git
       Folder (Repos) linked to the workspace.
    3. Triggers a job rerun via the Databricks Jobs REST API::

           POST /api/2.1/jobs/run-now
           {"job_id": "<job_id>"}

    Parameters
    ----------
    state:
        Current pipeline state.  Reads ``job_id``, ``proposed_sql_fix``, and
        ``proposed_pyspark_fix``.

    Returns
    -------
    dict
        ``{"status_message": str}`` summarising the applied fix.
    """
    print(
        f"[{state['job_id']}] 🚀  Deploy: "
        "Applying fix to production and restarting Databricks job..."
    )

    # --- Production replacement -------------------------------------------
    # if state["proposed_sql_fix"] != "None":
    #     await mcp_databricks.run_sql(state["proposed_sql_fix"])
    # await databricks_git.commit_and_push(state["proposed_pyspark_fix"])
    # await databricks_jobs_api.run_now(job_id=state["job_id"])
    # ----------------------------------------------------------------------

    await asyncio.sleep(1)

    msg = (
        f"Schema drift resolved for job {state['job_id']}. "
        f"Applied DDL: {state['proposed_sql_fix']}. "
        "Databricks job restarted successfully."
    )
    print(f"   -> {msg}")
    return {"status_message": msg}


# ---------------------------------------------------------------------------
# Routing logic
# ---------------------------------------------------------------------------

def route_after_qa(state: DatabricksPipelineState) -> str:
    """Conditional edge: route to 'deploy' on QA pass, 'rewrite' on failure.

    The ``"rewrite"`` branch loops back to ``engineer_agent`` so the engineer
    can produce an explicit ``ALTER TABLE`` fix after the QA Agent rejects the
    initial ``mergeSchema`` approach.

    Parameters
    ----------
    state:
        Current pipeline state.  Reads ``qa_passed``.

    Returns
    -------
    str
        ``"deploy"`` or ``"rewrite"``.
    """
    if state.get("qa_passed"):
        return "deploy"
    return "rewrite"


# ---------------------------------------------------------------------------
# Graph compilation
# ---------------------------------------------------------------------------

def build_graph() -> StateGraph:
    """Compile and return the LangGraph StateGraph for the healing workflow.

    Graph topology::

        START → detective → engineer → qa ─(pass)─→ deploy → END
                                ↑          │
                                └──(fail)───┘

    Returns
    -------
    StateGraph
        A compiled, runnable LangGraph graph.
    """
    graph = StateGraph(DatabricksPipelineState)

    graph.add_node("detective", detective_agent)
    graph.add_node("engineer", engineer_agent)
    graph.add_node("qa", qa_agent)
    graph.add_node("deploy", deployment_agent)

    graph.add_edge(START, "detective")
    graph.add_edge("detective", "engineer")
    graph.add_edge("engineer", "qa")

    graph.add_conditional_edges(
        "qa",
        route_after_qa,
        {"deploy": "deploy", "rewrite": "engineer"},
    )

    graph.add_edge("deploy", END)

    return graph.compile()


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

async def run_healing_workflow(job_id: str, error_logs: str) -> dict:
    """Run the full self-healing workflow for a failed Databricks job.

    Parameters
    ----------
    job_id:
        The Databricks job ID that triggered the failure alert.
    error_logs:
        Raw log text from the failed job run (used by the Detective Agent).

    Returns
    -------
    dict
        Final ``DatabricksPipelineState`` after all agents have completed.
    """
    app = build_graph()

    initial_state: DatabricksPipelineState = {
        "job_id": job_id,
        "error_logs": error_logs,
        "drift_details": "",
        "proposed_sql_fix": "",
        "proposed_pyspark_fix": "",
        "fix_strategy": "",
        "qa_passed": False,
        "qa_feedback": "",
        "status_message": "",
    }

    print(f"\n{'='*60}")
    print(f" Self-Healing Workflow started for job: {job_id}")
    print(f"{'='*60}\n")

    final_state = await app.ainvoke(initial_state)

    print(f"\n{'='*60}")
    print(f" Workflow complete. Status: {final_state['status_message']}")
    print(f"{'='*60}\n")

    return final_state


# ---------------------------------------------------------------------------
# Local smoke-test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    sample_logs = (
        "AnalysisException: A schema mismatch detected when writing to the "
        "Delta table 'main.sales.customers'.\n"
        "To enable schema migration using DataFrameWriter or DataStreamWriter, "
        "please set:\n"
        "  '.option(\"mergeSchema\", \"true\")'\n"
        "Table schema:\n"
        "  root\n"
        "   |-- customer_id: integer\n"
        "   |-- name: string\n"
        "Data schema:\n"
        "  root\n"
        "   |-- customer_id: integer\n"
        "   |-- name: string\n"
        "   |-- loyalty_tier: string   <-- NEW\n"
    )

    asyncio.run(run_healing_workflow(job_id="98765", error_logs=sample_logs))
